export const sitePetConfig = {
  storageKey: 'midimily.sitePet.closed',
  sessionPromptKey: 'midimily.sitePet.sessionPrompts',
  mobileMediaQuery: '(max-width: 767px)',
  showMobileEntry: true,
  maxAutoPromptsPerVisit: 2,
  initialBubbleMs: 7200,
  clickBubbleMs: 6800,
  sectionBubbleMs: 6400,
  sectionPromptCooldownMs: 14000,
  desktopScale: 0.46,
  mobileEntryScale: 0.28,
  spriteSrc: '/assets/pets/crimson-whoop/spritesheet.webp',
  defaultAnimation: 'idle',
  clickAnimation: 'waving',
  waitingAnimation: 'waiting',
  waitingAfterMs: 9000,
  desktopBoundsPadding: {
    top: 92,
    right: 26,
    bottom: 126,
    left: 20,
  },
  mobileBoundsPadding: {
    top: 84,
    right: 16,
    bottom: 22,
    left: 16,
  },
};
